[package]
name = "rusty-box"
version = "0.1.0"
authors = ["Amr Hassan <amr.hassan@gmail.com>"]

[dependencies]
quickcheck = "0.4.1"
nonsmallnum = "0.0.7-alpha.3"
graphic = "0.0.1-alpha.1"
enum_traits        = "*"
enum_traits_macros = "*"
